services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./

    env_file:
      - .env

    ports:
      - "8001:8000"
    depends_on:
      - pg
      - redis

  pg:
    image: postgres:17.6-bookworm
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: killchik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - pg

  redis:
    image: redis:8.2.1-alpine
    container_name: cache_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: